# Continuous Integration (CI) to Build & Test & Coverage & Lint.
# ~~
name: CI
on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ '**' ]

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: '11'
          cache: 'sbt'

      - name: Validate Code
        run: sbt validateCode

  build:
    name: Build & Test
    needs: [ validate ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: '11'
          cache: 'sbt'

      - name: Build & Test
        run: sbt testWithCoverage

      - name: Upload coverage report (Cobertura)
        uses: actions/upload-artifact@v3.1.0
        with:
          name: cobertura.xml
          path: ${{github.workspace}}/target/scala-2.13/coverage-report/cobertura.xml

      - name: Upload coverage report (HTML)
        uses: actions/upload-artifact@v3.1.0
        with:
          name: scoverage-report-html
          path: ${{github.workspace}}/target/scala-2.13/scoverage-report/

  coverage:
    name: Coverage Report
    if: ${{ github.event.pull_request }}
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: cobertura.xml

      - name: Analyzing coverage report
        uses: 5monkeys/cobertura-action@master
        with:
          path: cobertura.xml
          only_changed_files: true
          fail_below_threshold: true
          show_missing: true
          show_line: true
          show_branch: true
          show_class_names: true
          link_missing_lines: true
          minimum_coverage: 75
